# Generated by Django 5.0 on 2023-12-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_project_author_project_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("backend", "Backend"),
                    ("frontend", "Frontend"),
                    ("ios", "IOS"),
                    ("android", "Android"),
                ],
                max_length=65,
            ),
        ),
    ]
