# Generated by Django 5.0 on 2023-12-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_project_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
