# Generated by Django 5.0 on 2023-12-27 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_contributor_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("user", "project")},
        ),
    ]
