# Generated by Django 5.0 on 2024-01-02 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_contributor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assign_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.contributor'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.project'),
        ),
    ]
