# Generated by Django 5.0 on 2024-01-06 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_issue_assign_to_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.contributor",
            ),
        ),
    ]
